package com.sjl.springmvc.dao;

import com.sjl.springmvc.model.DbUserType;
import java.util.List;

public interface DbUserTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int insert(DbUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    DbUserType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    List<DbUserType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user_type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int updateByPrimaryKey(DbUserType record);
}