package com.sjl.springmvc.dao;

import com.sjl.springmvc.model.DbUser;
import java.util.List;

public interface DbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int insert(DbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    DbUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    List<DbUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_user
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    int updateByPrimaryKey(DbUser record);
}