package com.sjl.springmvc.model;

public class DbUserType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user_type.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user_type.name
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user_type.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user_type.id
     *
     * @return the value of db_user_type.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user_type.id
     *
     * @param id the value for db_user_type.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user_type.name
     *
     * @return the value of db_user_type.name
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user_type.name
     *
     * @param name the value for db_user_type.name
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user_type.type
     *
     * @return the value of db_user_type.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user_type.type
     *
     * @param type the value for db_user_type.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }
}