package com.sjl.springmvc.model;

public class DbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.username
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.password
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.nickname
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_user.image
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.id
     *
     * @return the value of db_user.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.id
     *
     * @param id the value for db_user.id
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.username
     *
     * @return the value of db_user.username
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.username
     *
     * @param username the value for db_user.username
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.password
     *
     * @return the value of db_user.password
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.password
     *
     * @param password the value for db_user.password
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.nickname
     *
     * @return the value of db_user.nickname
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.nickname
     *
     * @param nickname the value for db_user.nickname
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.type
     *
     * @return the value of db_user.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.type
     *
     * @param type the value for db_user.type
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_user.image
     *
     * @return the value of db_user.image
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_user.image
     *
     * @param image the value for db_user.image
     *
     * @mbggenerated Tue Mar 05 21:53:22 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}